### PR TITLE
Update 03-dplyr-tidyr.Rmd

### PR DESCRIPTION
**Pull request by DanielaGawehns**
Proposing a change regarding the deprecated "path" argument.
(and hoping that I am following the contribution guidelines with this request.)

### CODE REVIEW

**Comment by kelseygonzalez** [comment]
Great catch, @DanielaGawehns . I don't know how long it would have taken for me to notice this. 

@atheobold and @juanfung - Should we leave this as a descriptor and an alternative chunk of code as Daniela has or go a little further and remove the mentions of the functional argument `path` instead. I ask because one of the teaching principles of the carpentries is to (try to) not teach multiple ways to accomplish the same task, and because `path=` is deprecated we might as well just teach the updated way!

**Comment by juanfung** [comment]
@DanielaGawehns Thanks for catching this. It's weird, because I thought I'd committed a change to address this! My solution was to forgo the explicit named argument altogether:
```
write_csv(interviews_plotting, "data_output/interviews_plotting.csv")
```
I don't think using named argument is necessary here. @kelseygonzalez, @atheobold  ?

**Comment by kelseygonzalez** [comment]
Hm, @juanfung 's comment makes the most sense given what we know about deprecation cycles. However, we would be relying on the assumption that instructors have taught the students if you include unnamed implicit arguments you are reliant on the default ordering of the function. I tend to be explicit when I name arguments when I teach for this reason, but don't have any strong objection. I'll leave the final decision to @atheobold when she joins the conversation.

**Comment by atheobold** [comment]
I tend to agree with @kelseygonzalez, and favor teaching people to use argument names to functions. I have a theory that this helps people better understand functions when they go to write them, but that has yet to be tested. While using a named argument makes it a bit more effort on our end to make sure the argument is current, I would lean towards including it.

**Review by kelseygonzalez — APPROVED** [review]

**Pull request merged**
