### PR TITLE
change words to British spelling conventions

### PR DESCRIPTION
**Pull request by maneesha**
This changes the words "color" and "favorite" to the British spellings "colour" and "favourite."  Note this only applies to the narrative text.  I noticed there are places in the code where sometimes it is `color` and sometimes `colour` and have not edited those.  Does R treat those words differently?

### CODE REVIEW

**Comment by angela-li** [comment]
Both British English and American English spellings work for ggplot2, but the main text on teaching intro ggplot2, [R for Data Science](https://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings), uses American English as convention, and has a note that "colour" is also fine (see below). It could be worth it to note somewhere in the lesson that both are ok.

image

**Comment by juanfung** [comment]
@angela-li What's the status on this?

**Comment by kelseygonzalez** [comment]
Quick update: @angela-li and I have reached out to the broader Carpentries R Maintainers to clarify how other maintainers are defaulting to British versus American spellings of dplyr functions. We're getting clarification if we should default to British spellings in R code, since the [Carpentries style guide](https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html) recommends British spellings. 

Thanks for bringing this to our attention @maneesha . We're working on getting this resolved.

**Comment by kelseygonzalez** [comment]
The maintainers and greater carpentry community decided to maintain the British spelling in prose (thanks to @maneesha for pointing these out!) and keep with American spelling in code. We added a note to the `dplyr` lesson to point out that the spelling default of these different commands (like *summarize()* versus *summarise()*) can be determined by the instructor and the region of instruction.

**Review by atheobold — APPROVED** [review]
Nice catch with centre!

**Pull request merged**
