### PR TITLE
Add tibble language earlier in 02 lesson (Issue #71)

### PR DESCRIPTION
**Pull request by potterzot**
This PR includes potential new language in response to issue #71 that I've raised with regard to the discussion of data frames and tibbles in the [second lesson "What are data frames" section](https://github.com/datacarpentry/r-socialsci/blob/gh-pages/_episodes_rmd/02-starting-with-data.Rmd#what-are-data-frames).

(Submitted as part of instructor checkout.)

### CODE REVIEW

**Comment by ErinBecker** [comment]
@potterzot - thanks for this. This looks like a great clarification to me. I taught this lesson yesterday and some of the learners were confused about the output when working with tibbles. I think this would help.

**Comment by juanfung** [comment]
@potterzot and @ErinBecker  I like this new language, and the idea of clarifying what tibbles are earlier. My only question is whether we should introduce tibbles, as extensions of dataframes, *before* introducing dataframes. 

So my suggestion is something like this:
```
Data frames are the _de facto_ data structure ...

A data frame is the representation of data ...

A data frame can be created by hand, but ...

A tibble is an extension of ...

As a tibble, the type of data ...
```
Also, we should be consistent about using ``tibble`` (with back ticks) and tibble (no back ticks).

Thoughts?

**Comment by potterzot** [comment]
@juanfung I struggled with that too. It does make sense to me to introduce data.frames first, but as a result of using `read_csv` from the tidyverse, all output is displayed as tibbles, which is where the confusion arises I think.

One thing we could do would be to introduce data.frames before actually reading the data in, and then go on to describe tibbles by looking at the data. So using your example,

```
Data frames are the _de facto_ data structure ...

A data frame is the representation of data ...

A data frame can be created by hand, but ...

<Do the read_csv() data import here.>

A tibble is an extension of ...

As a tibble, the type of data ..

<tibble summary code here.>
```

Or we could use `read.csv` to read in as a data.frame, discuss those, and then use `read_csv` to reload the data and look at the tibble version, but I fear that would be too long and also unnecessarily confuse people who are just being introduced to data.frames and tibbles.

**Comment by juanfung** [comment]
@potterzot Yes, I like your suggestion! I think this is clearer, and it presents the data frames as a *concept* (rather than an object unique to R).  

I agree that switching between `read.csv` and `read_csv` is unnecessary. Since the lesson leans heavily on the tidyverse, let's keep it simple.

**Comment by ErinBecker** [comment]
This all looks good to me!

**Comment by juanfung** [comment]
@potterzot Would you be able to make the change? If not, I can do it!

**Comment by potterzot** [comment]
I think I can get on this and submit a PR by Wednesday, would that work okay?

**Comment by juanfung** [comment]
No rush! You can just push another commit to your `add-tibble-language` branch, if you still have it. Otherwise, I can merge this PR and commit the change after.

**Pull request merged**
