### PR TITLE
 More explicit treatment of logical operators in dplyr's "filter" function

### PR DESCRIPTION
**Pull request by aranganath24**
This PR replaces commas with the "&" symbol within the filter function (in the "Selecting columns and filtering rows" section of the "Data wrangling with dplyr and tidyr" lesson) so as to make the code more explicit, and also provides an example of how the "or" logical operator (|) can be used within the filter function.

### CODE REVIEW

**Review by juanfung — APPROVED** [review]

**Comment by atheobold** [comment]
@aranganath24 & @juanfung -- I think these changes will confuse learners into thinking that the *only* way you can chain multiple filters together is with `&` operators, which is not the case. 

I was thinking of first having an explanation of how you can chain multiple filters together using `,`'s, which is what **dplyr** expects. Then, **after discussing commas**, it could be mentioned that an `&` operator could be used to perform the same procedure. Then, after these steps, the "or" operator could be discussed. 

I was envisioning something along these lines: <https://datacarpentry.org/semester-biology/materials/dplyr-adv-filter/>

**Review by atheobold — CHANGES_REQUESTED** [review]
(see previous comment)

**Comment by juanfung** [comment]
@atheobold Thanks for the link. I suppose a one-liner saying "you can also chain using `,` wouldn't hurt.

For the record, I don't see the value. We are introducing them to logical operators and how to form logical statements. The comma is not a logical operator and would never be used this way outside of dplyr. The danger of confusing them about the use of `&` is negligible, to me. 

That said, I'm okay if you want the comma in the lesson. 😜

**Comment by atheobold** [comment]
@juanfung -- Quite the friendly disagreement we have! I completely agree with your argument that this segment of the lesson should be teaching learners about how logical comparisons work. I think this is a **critical** part of this segment, but I don't think that it meets this need. If we are *truly* going to teach logical comparison, there should be a list of possible comparisons that are often made (like what is included in the `filter()` documentation). 

Something like: 

> == means “equal to”
!= means “not equal to”
> or < means “greater than” or “less than”
>= or <= means “greater than or equal to” or “less than or equal to”

Personally, I teach "data science" in R using the specific arguments that each function expects. **dplyr** accepts *both* `&` and `,` for filtering, so I think both should be discussed. Structurally, I believe commas are easier to read, since they promote 
nice formatting of the code. 

I feel comfortable following a similar style to the Data Carpentry for Biologists "Advanced Filtering" lesson, since it teaches both `,` and `&`, as well as `|`. I think a great additional contribution would be adding a list of possible comparisons that can be made. The `between()` and `near()` functions would be great to mention, too!

**Comment by juanfung** [comment]
@atheobold If we don't explain symbols like `==` anywhere else, then yes we should add an explanation.

Now, I know said I was okay the comma discussion, but I just want to point out a case I stumbled on where learning the comma as equivalent to `&` is problematic for generalization (even if here we emphasize this is for `dplyr::filter`).
```
dplyr::select(starts_with('village'), ends_with('meals'))
```
is not equivalent to
```
dplyr::select(starts_with('village') & ends_with('meals'))
```
The fact that comma for chaining AND statements is so specific to `dplyr::filter` seems problematic to me. Having taught other workshops, I think it's tricky to overload learners with information. Nevertheless, having never taught *this* workshop myself, I will defer to your judgement.

**Review by atheobold — APPROVED** [review]
These are great changes! I added a sentence describing what an "and" statement does, since you had one for an "or" statement. It may look like I made a lot of changes, but it was mostly adding in line breaks wider than 80 characters.

**Pull request merged**
