### PR TITLE
adding glimpse() function to the inspecting data frames section

### LINKED ISSUE #265: Introduce glimpse in "Starting with Data"
Per #260, using `tibble::glimpse` to peek at parsed json tibble. It would be nice to introduce `glimpse` in Starting with Data episode.

### PR DESCRIPTION
**Pull request by nataliablock**
This PR resolves #265 

Please, make any changes if you think is necessary. Feel free to contact me if needed.

Thank you!

### CODE REVIEW

**Comment by nataliablock** [comment]
Sorry, it's the first time I'm doing a contribution and I'm not sure what went wrong. Anyone could help me with this?

**Comment by kelseygonzalez** [comment]
Hi @nataliablock  - I assume your second comment is referring to the failing build. Don't worry about that for now - it's an error on our side, not yours. We'll take a look at this soon!

**Comment by nataliablock** [comment]
Yes, that was about the failing build. Thanks for the clarification @kelseygonzalez !

**Comment by kelseygonzalez** [comment]
I really liked your contribution, @nataliablock ! I edited it slightly for clarification. When I pushed my edits, my machine somehow auto-edited a bunch of extra periods, just FYI to the other maintainers. @atheobold or @juanfung , could you approve our changes?

**Review by atheobold — APPROVED** [review]
This change looks great @nataliablock! Thanks for adding this to the lesson! It's been on the TODO list for too long!

**Pull request merged**
