### PR TITLE
Checkout: setup tidyverse library

### PR DESCRIPTION
**Pull request by carlosug**
_This contribution is part of the checkout process_

For some reason I was unable to install  `tidyverse` package at the beginning. I have made a minor change at the setup [episode](https://datacarpentry.org/r-socialsci/setup.html).

 Eased `c()` function within `install.package`.

Let me know if I am in the right direction with such contribution.

Thanks!

Carlos.

### CODE REVIEW

**Comment by kelseygonzalez** [comment]
Hi @carlosug - I'm one of the lesson maintainers. Thanks so much for taking the time to contribute to this less. 

I'm happy with adding periods at the end of the bullet points to make it consistent, as it was not consistent before. However, adding c() around the package name in `install.packages()` shouldn't make a different to my understanding, so I don't think this is a change we should make. At the end of the day, it makes the code harder to read and understand for first-time users.

**Comment by kelseygonzalez** [comment]
After looking at the changes again, I realize that @carlosug is actually implementing a clever change - they are removing the `c()` from around the package name instead of adding it. I read it backwards. I'm all for this change as I mentioned above, it makes it easier for first-time R users to implement. Thanks again for your contribution @carlosug .

**Comment by atheobold** [comment]
I agree! The `c( )` function should only be used if we were installing multiple packages at the same time, which the lesson is not. Good catch @carlosug!

**Comment by carlosug** [comment]
Thank you folks!!!

**Pull request merged**
