### PR TITLE
Introduction to Long/Wide Data

### PR DESCRIPTION
**Pull request by atheobold**
In these changes I've added a section that gives an overview of the long and wide data formats, incorporating the gif created by @kelseygonzalez.

### CODE REVIEW

**Comment by kelseygonzalez** [comment]
When trying to preview these changes, in the 03-dplyr-tidyr.Rmd doc lines 647-664 the chunk is failing to render because `object 'interviews_long' not found`. Could you debug this and recommit @atheobold ?

**Comment by atheobold** [comment]
Thanks for pointing this out @kelseygonzalez! The issue was the use of the `vars()` function inside the `pivot_longer()` function.

**Review by kelseygonzalez — APPROVED** [review]
I've reviewed the changes and like the contribution. I'm ready to merge it in, waiting on @juanfung 's review.

**Review by juanfung — APPROVED** [review]
Looks good to me. And I appreciate your use of sensible line wrapping 👍

**Pull request merged**
