### PR TITLE
removed excessive use of # for comments

### PR DESCRIPTION
**Pull request by steltenpower**
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
instructor.training@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by atheobold** [comment]
@steltenpower -- I wouldn't deem the use of more than one # "excessive". The number of #s a person uses for their code commenting is arguably a matter of personal style. I don't believe removing these two "extra" hashes is necessary and improves the lesson's contents.

**Comment by steltenpower** [comment]
The one thing I really cared about is the differrence between 0 or 1 times # ...

I was wondering if there should be any # in the line
# view(interviews)

Should it be 'turned off' by making it a comment?

**Comment by juanfung** [comment]
@steltenpower i think it can be removed completely as the chunk is set to `results=`hide'`. we're just reloading our packages and data here. If you'd like to update the PR to remove those two lines, that would be great!

**Comment by zkamvar** [comment]
A bit of context for those who might be wondering why some folks may prefer two `##` over a single `#`: It's a convention from emacs (editor) that affects how the comments are indented. I believe single comments were used for information and double comments were used for commented-out code. Most people now use double comments just to prevent emacs from indenting their comments and make no distinction between the two. 

Source: https://mail.python.org/pipermail/python-list/2002-October/143369.html

**Comment by juanfung** [comment]
i've been outed!

**Pull request closed without merging**
